# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xc3ReLIc-QGA0qwCgzg96vqz5OhZ3IUn
"""

def kasallik_tashxisi(belgi):
 if belgi =="Istima":
  return "Parestamol iching "
 elif belgi=="Bosh og'rig'i":
  return "Bolnol"
 elif belgi=="Ko'z og'rig'i":
  return "Fratsilin"
 elif belgi=="Qol og'rig'i":
  return "Kupen"
 elif belgi=="Tomoq og'rig'i":
  return "girip xot"
 elif belgi=="Qorin og'rig'i":
  return "Lineks iching"
 elif belgi=="bog'im og'rig'i":
  return "Artoksan"
 elif belgi=="Oshqozon og'rishi" :
  return "Ibukin"
 elif belgi=="Jigar seryozi":
  return "Rinza"
 elif belgi =="Tish og'rig'i":
  return "Senepar"
 else:
  return "SHifoxonaga murojat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def sport_turlari(belgi):
 if belgi=="Futbol":
  return "45 minutdan 2 tayam davom etadi"
 elif belgi=="basketbol":
  return "10 minutdan 4 tayam davom etadi "
 elif belgi=="Volebol":
  return "15 minutdan 3 partiya davom etadi "
 elif belgi=="Xokkey":
  return "8 munutdan 6 tayam davom etadi "
 elif belgi=="Boks":
  return "3 minutdan 12 round davom etadi "
 else:
   return"sport turlariga murijat qiling "
 belgi=input("sport turini kiriting")
 natija=sport_turlari(belgi)
 print(natija)